# Generated by Django 5.2.15 on 2026-06-11 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0005_alter_car_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, help_text='XXXX XXXX XXXX XXXX', max_length=19)),
                ('card_expiry', models.CharField(blank=True, help_text='MM/YY', max_length=5)),
                ('card_holder', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('FULL', 'Paid in Full'), ('INSTALLMENT', 'Installment Plan')], max_length=20)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('ACTIVE', 'Active Installment'), ('COMPLETED', 'Completed Installment')], max_length=20)),
                ('final_price', models.IntegerField()),
                ('installment_months', models.IntegerField(blank=True, choices=[(12, '12 Months'), (24, '24 Months')], null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
